version: '3.4'

services:
  microfrontendserverwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    image: ${DOCKER_REGISTRY-}microfrontendserverwebapi
    build:
      context: .
      dockerfile: MicrofrontendServer.Web.API/Dockerfile