services:
  discover-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: MicrofrontendServer.Web.Discover/Dockerfile
  order-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: MicrofrontendServer.Web.Order/Dockerfile